/**
 * Ordered object of stats
 * @type {{[key:string]: {
 *   name: string
 *   nameLore: string // name found in items lore
 *   nameShort: string // up to 16 chars
 *   nameTiny: string // up to 6 chars
 *   symbol: string
 *   suffix: string
 *   color: string
 * }}}
 */
export const STATS_DATA = {
  health: {
    name: "生命",
    nameLore: "生命",
    nameShort: "生命",
    nameTiny: "HP",
    symbol: "❤",
    suffix: "",
    color: "c",
  },
  defense: {
    name: "防御",
    nameLore: "防御",
    nameShort: "防御",
    nameTiny: "Def",
    symbol: "❈",
    suffix: "",
    color: "a",
  },
  strength: {
    name: "力量",
    nameLore: "力量",
    nameShort: "力量",
    nameTiny: "Str",
    symbol: "❁",
    suffix: "",
    color: "c",
  },
  speed: {
    name: "速度",
    nameLore: "速度",
    nameShort: "速度",
    nameTiny: "Spd",
    symbol: "✦",
    suffix: "",
    color: "f",
  },
  crit_chance: {
    name: "暴击几率",
    nameLore: "暴击几率",
    nameShort: "暴击几率",
    nameTiny: "CC",
    symbol: "☣",
    suffix: "%",
    color: "9",
  },
  crit_damage: {
    name: "暴击伤害",
    nameLore: "暴击伤害",
    nameShort: "暴击伤害",
    nameTiny: "CD",
    symbol: "☠",
    suffix: "%",
    color: "9",
  },
  intelligence: {
    name: "智力",
    nameLore: "智力",
    nameShort: "智力",
    nameTiny: "Int",
    symbol: "✎",
    suffix: "",
    color: "b",
  },
  bonus_attack_speed: {
    name: "额外攻击速度",
    nameLore: "额外攻击速度",
    nameShort: "额外攻击速度",
    nameTiny: "Atk",
    symbol: "⚔",
    suffix: "%",
    color: "e",
  },
  sea_creature_chance: {
    name: "海怪钓出概率",
    nameLore: "海怪钓出概率",
    nameShort: "海怪概率",
    nameTiny: "SCC",
    symbol: "α",
    suffix: "%",
    color: "3",
  },
  magic_find: {
    name: "Magic Find",
    nameLore: "Magic Find",
    nameShort: "Magic Find",
    nameTiny: "MF",
    symbol: "✯",
    suffix: "",
    color: "b",
  },
  pet_luck: {
    name: "宠物幸运",
    nameLore: "宠物幸运",
    nameShort: "宠物幸运",
    nameTiny: "PL",
    symbol: "♣",
    suffix: "",
    color: "d",
  },
  true_defense: {
    name: "真实防御",
    nameLore: "真实防御",
    nameShort: "真实防御",
    nameTiny: "TD",
    symbol: "❂",
    suffix: "",
    color: "f",
  },
  ferocity: {
    name: "凶猛",
    nameLore: "凶猛",
    nameShort: "凶猛",
    nameTiny: "Frc",
    symbol: "⫽",
    suffix: "",
    color: "c",
  },
  ability_damage: {
    name: "技能伤害",
    nameLore: "技能伤害",
    nameShort: "技能伤害",
    nameTiny: "AD",
    symbol: "๑",
    suffix: "%",
    color: "c",
  },
  mining_speed: {
    name: "挖掘速度",
    nameLore: "挖掘速度",
    nameShort: "挖掘速度",
    nameTiny: "MngSpd",
    symbol: "⸕",
    suffix: "",
    color: "6",
  },
  mining_fortune: {
    name: "挖矿时运",
    nameLore: "挖矿时运",
    nameShort: "挖矿时运",
    nameTiny: "MngFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  farming_fortune: {
    name: "作物时运",
    nameLore: "作物时运",
    nameShort: "作物时运",
    nameTiny: "FrmFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  foraging_fortune: {
    name: "木业时运",
    nameLore: "木业时运",
    nameShort: "木业时运",
    nameTiny: "FrgFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  pristine: {
    name: "宝石浓缩",
    nameLore: "宝石浓缩",
    nameShort: "宝石浓缩",
    nameTiny: "Prs",
    symbol: "✧",
    suffix: "",
    color: "5",
  },
  fishing_speed: {
    name: "钓鱼速度",
    nameLore: "钓鱼速度",
    nameShort: "钓鱼速度",
    nameTiny: "FS",
    symbol: "☂",
    suffix: "",
    color: "b",
  },
  breaking_power: {
    name: "破坏力",
    nameLore: "破坏力",
    nameShort: "破坏力",
    nameTiny: "BP",
    symbol: "Ⓟ",
    suffix: "",
    color: "2",
  },
  health_regen: {
    name: "生命恢复",
    nameLore: "生命恢复",
    nameShort: "生命恢复",
    nameTiny: "HPR",
    symbol: "❣",
    suffix: "",
    color: "c",
  },
  vitality: {
    name: "活力",
    nameLore: "活力",
    nameShort: "活力",
    nameTiny: "Vit",
    symbol: "♨",
    suffix: "",
    color: "5",
  },
  mending: {
    name: "吸收力",
    nameLore: "吸收力",
    nameShort: "吸收力",
    nameTiny: "Mend",
    symbol: "☄",
    suffix: "",
    color: "a",
  },
  // todo: remove this once #1639 is merged and update wisdom values
  wisdom: {
    name: "Wisdom",
    nameLore: "Wisdom",
    nameShort: "Wisdom",
    nameTiny: "W",
    symbol: "☯",
    suffix: "",
    color: "3",
  },
  mana_regen: {
    name: "能量恢复",
    nameLore: "能量恢复",
    nameShort: "能量恢复",
    nameTiny: "MPR",
    symbol: "🗲",
    suffix: "",
    color: "b",
  },
  rift_time: {
    name: "裂谷时间",
    nameLore: "裂谷时间",
    nameShort: "裂谷时间",
    nameTiny: "RT",
    symbol: "ф",
    suffix: "",
    color: "a",
  },
  undead: {
    name: "Undead",
    nameLore: "Undead",
    nameShort: "Undead",
    nameTiny: "U",
    symbol: "༕",
    suffix: "",
    color: "2",
  },
};

const symbols = {
  powder: "᠅",
  soulflow: "⸎",
  dungeon_upgrade: "⚚",
  dye: "✿",
};
for (const stat in STATS_DATA) {
  symbols[stat] = STATS_DATA[stat].symbol;
}
export const SYMBOLS = symbols;

// todo: grab these constants from src/constants/misc: base_stats, stat_template
